spring.application.name=food-ordering
spring.config.import=optional:file:.env[.properties]
spring.profiles.default=dev
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/food_ordering}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#spring.security.user.name=admin
#spring.security.user.password=admin123
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*}
app.timezone=${APP_TIMEZONE:Europe/Belgrade}
