CREATE TABLE loyalty_program (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivo VARCHAR(255) NOT NULL,
    popust DOUBLE PRECISION NOT NULL,
    prag_bodova INTEGER NOT NULL
);

CREATE TABLE korisnik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    lozinka VARCHAR(255) NOT NULL,
    broj_bodova DOUBLE PRECISION NOT NULL,
    loyalty_program_id BIGINT,
    uloga VARCHAR(255) NOT NULL,
    CONSTRAINT fk_korisnik_loyalty_program
        FOREIGN KEY (loyalty_program_id) REFERENCES loyalty_program(id)
);

CREATE TABLE proizvod (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR(255) NOT NULL,
    tip VARCHAR(255),
    cena DOUBLE PRECISION NOT NULL,
    jedinica_mere VARCHAR(255),
    kalorije DOUBLE PRECISION NOT NULL,
    proteini DOUBLE PRECISION NOT NULL,
    masti DOUBLE PRECISION NOT NULL,
    ugljeni_hidrati DOUBLE PRECISION NOT NULL
);

CREATE TABLE porudzbine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum TIMESTAMP(6) NOT NULL,
    ukupan_iznos DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL,
    originalna_cena DOUBLE PRECISION NOT NULL,
    korisnik_id BIGINT
);

CREATE TABLE stavka_porudzbine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kolicina DOUBLE PRECISION NOT NULL,
    cena DOUBLE PRECISION NOT NULL,
    iznos_stavke DOUBLE PRECISION NOT NULL,
    porudzbina_id BIGINT NOT NULL,
    proizvod_id BIGINT NOT NULL,
    CONSTRAINT fk_stavka_porudzbine_porudzbina
        FOREIGN KEY (porudzbina_id) REFERENCES porudzbine(id),
    CONSTRAINT fk_stavka_porudzbine_proizvod
        FOREIGN KEY (proizvod_id) REFERENCES proizvod(id)
);

CREATE INDEX idx_porudzbine_korisnik_id ON porudzbine(korisnik_id);
