CREATE TABLE radno_vreme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dan VARCHAR(255) NOT NULL,
    od_vremena TIME NOT NULL,
    do_vremena TIME NOT NULL,
    aktivno BOOLEAN NOT NULL DEFAULT TRUE
);

-- Indeks za brže pretraživanje po danu
CREATE INDEX idx_radno_vreme_dan ON radno_vreme(dan);

-- Indeks za pretraživanje aktivnih radnih vremena
CREATE INDEX idx_radno_vreme_aktivno ON radno_vreme(aktivno);
