-- @formatter:off
-- noinspection SqlResolveForFile
CREATE TABLE alergen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR(255) NOT NULL UNIQUE,
    opis TEXT
);

-- Join tabela za ManyToMany vezu između proizvoda i alergena
CREATE TABLE proizvod_alergen (
    proizvod_id BIGINT NOT NULL,
    alergen_id BIGINT NOT NULL,
    PRIMARY KEY (proizvod_id, alergen_id),
    CONSTRAINT fk_proizvod_alergen_proizvod
        FOREIGN KEY (proizvod_id) REFERENCES proizvod(id) ON DELETE CASCADE,
    CONSTRAINT fk_proizvod_alergen_alergen
        FOREIGN KEY (alergen_id) REFERENCES alergen(id) ON DELETE CASCADE
);

-- Indeksi za brže pretraživanje
CREATE INDEX idx_proizvod_alergen_proizvod ON proizvod_alergen(proizvod_id);
CREATE INDEX idx_proizvod_alergen_alergen ON proizvod_alergen(alergen_id);
CREATE INDEX idx_alergen_naziv ON alergen(naziv);
