CREATE TABLE omiljena_porudzbina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    korisnik_id BIGINT NOT NULL,
    naziv VARCHAR(255) NOT NULL,
    datum_kreiranja TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_omiljena_porudzbina_korisnik
        FOREIGN KEY (korisnik_id) REFERENCES korisnik(id) ON DELETE CASCADE
);

CREATE TABLE omiljena_porudzbina_stavka (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    omiljena_porudzbina_id BIGINT NOT NULL,
    proizvod_id BIGINT NOT NULL,
    kolicina DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_omiljena_porudzbina_stavka_omiljena
        FOREIGN KEY (omiljena_porudzbina_id) REFERENCES omiljena_porudzbina(id) ON DELETE CASCADE,
    CONSTRAINT fk_omiljena_porudzbina_stavka_proizvod
        FOREIGN KEY (proizvod_id) REFERENCES proizvod(id)
);

CREATE INDEX idx_omiljena_porudzbina_korisnik_id ON omiljena_porudzbina(korisnik_id);
CREATE INDEX idx_omiljena_porudzbina_stavka_omiljena_id ON omiljena_porudzbina_stavka(omiljena_porudzbina_id);
