CREATE TABLE notifikacija (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    korisnik_id BIGINT NOT NULL,
    poruka TEXT NOT NULL,
    tip VARCHAR(64) NOT NULL DEFAULT 'RUCNO',
    procitana BOOLEAN NOT NULL DEFAULT FALSE,
    datum TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notifikacija_korisnik
        FOREIGN KEY (korisnik_id) REFERENCES korisnik(id) ON DELETE CASCADE
);

CREATE INDEX idx_notifikacija_korisnik_datum ON notifikacija(korisnik_id, datum);
CREATE INDEX idx_notifikacija_korisnik_procitana ON notifikacija(korisnik_id, procitana);
CREATE INDEX idx_notifikacija_tip ON notifikacija(tip);
